FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY target/Pipeline-0.0.1-SNAPSHOT.jar app.jar
COPY wait-for-postgres.sh wait-for-postgres.sh
RUN chmod +x wait-for-postgres.sh

EXPOSE 8080

ENTRYPOINT ["./wait-for-postgres.sh", "postgres", "5432", "java -jar app.jar"]
